#############################################################################
# Makefile for building: x86emu-qt
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  x86emu-qt.pro
# Template: lib
# Command: C:\Program\Qt\5.3\msvc2010_opengl\bin\qmake.exe -o Makefile x86emu-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Program\Qt\5.3\msvc2010_opengl\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: x86emu-qt.pro ..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\win32-msvc2010\qmake.conf ..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\spec_pre.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\common\shell-win32.conf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\qconfig.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_enginio.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_enginio_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkit.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkit_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\qt_functions.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\qt_config.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\qt_config.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\win32-msvc2010\qmake.conf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\spec_post.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\default_pre.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\default_pre.prf \
		x86emu-qt.pri \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\resolve_config.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\default_post.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\rtti.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\precompile_header.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\warn_on.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\qt.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\resources.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\moc.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\opengl.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\uic.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\windows.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\testcase_targets.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\exceptions.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\yacc.prf \
		..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\lex.prf \
		x86emu-qt.pro \
		C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Widgets.prl \
		C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Xml.prl \
		C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Gui.prl \
		C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Core.prl
	$(QMAKE) -o Makefile x86emu-qt.pro
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\spec_pre.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\common\shell-win32.conf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\qconfig.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_enginio.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkit.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\qt_functions.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\qt_config.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\qt_config.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\win32-msvc2010\qmake.conf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\spec_post.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\default_pre.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\default_pre.prf:
x86emu-qt.pri:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\resolve_config.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\exclusive_builds_post.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\default_post.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\rtti.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\precompile_header.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\warn_on.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\qt.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\resources.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\moc.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\opengl.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\uic.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\win32\windows.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\testcase_targets.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\exceptions.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\yacc.prf:
..\..\..\..\Program\Qt\5.3\msvc2010_opengl\mkspecs\features\lex.prf:
x86emu-qt.pro:
C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Widgets.prl:
C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Xml.prl:
C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Gui.prl:
C:/Program/Qt/5.3/msvc2010_opengl/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile x86emu-qt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) x86emu-qt.exp
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
