#############################################################################
# Makefile for building: x86emu-qt
# Generated by qmake (2.01a) (Qt 4.8.6) on: sö 21. sep 00:48:39 2014
# Project:  x86emu-qt.pro
# Template: lib
# Command: c:\Program\Qt\bin\qmake.exe -o Makefile x86emu-qt.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\Program\Qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: x86emu-qt.pro  ..\..\..\..\Program\Qt\mkspecs\win32-msvc2010\qmake.conf ..\..\..\..\Program\Qt\mkspecs\qconfig.pri \
		..\..\..\..\Program\Qt\mkspecs\modules\qt_webkit_version.pri \
		..\..\..\..\Program\Qt\mkspecs\features\qt_functions.prf \
		..\..\..\..\Program\Qt\mkspecs\features\qt_config.prf \
		..\..\..\..\Program\Qt\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Program\Qt\mkspecs\features\default_pre.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\default_pre.prf \
		x86emu-qt.pri \
		..\..\..\..\Program\Qt\mkspecs\features\release.prf \
		..\..\..\..\Program\Qt\mkspecs\features\debug_and_release.prf \
		..\..\..\..\Program\Qt\mkspecs\features\default_post.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\default_post.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\rtti.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\exceptions.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\stl.prf \
		..\..\..\..\Program\Qt\mkspecs\features\shared.prf \
		..\..\..\..\Program\Qt\mkspecs\features\dll.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\..\..\Program\Qt\mkspecs\features\warn_on.prf \
		..\..\..\..\Program\Qt\mkspecs\features\qt.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\thread.prf \
		..\..\..\..\Program\Qt\mkspecs\features\moc.prf \
		..\..\..\..\Program\Qt\mkspecs\features\win32\windows.prf \
		..\..\..\..\Program\Qt\mkspecs\features\resources.prf \
		..\..\..\..\Program\Qt\mkspecs\features\uic.prf \
		..\..\..\..\Program\Qt\mkspecs\features\yacc.prf \
		..\..\..\..\Program\Qt\mkspecs\features\lex.prf
	$(QMAKE) -o Makefile x86emu-qt.pro
..\..\..\..\Program\Qt\mkspecs\qconfig.pri:
..\..\..\..\Program\Qt\mkspecs\modules\qt_webkit_version.pri:
..\..\..\..\Program\Qt\mkspecs\features\qt_functions.prf:
..\..\..\..\Program\Qt\mkspecs\features\qt_config.prf:
..\..\..\..\Program\Qt\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Program\Qt\mkspecs\features\default_pre.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\default_pre.prf:
x86emu-qt.pri:
..\..\..\..\Program\Qt\mkspecs\features\release.prf:
..\..\..\..\Program\Qt\mkspecs\features\debug_and_release.prf:
..\..\..\..\Program\Qt\mkspecs\features\default_post.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\default_post.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\rtti.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\exceptions.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\stl.prf:
..\..\..\..\Program\Qt\mkspecs\features\shared.prf:
..\..\..\..\Program\Qt\mkspecs\features\dll.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\..\..\Program\Qt\mkspecs\features\warn_on.prf:
..\..\..\..\Program\Qt\mkspecs\features\qt.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\thread.prf:
..\..\..\..\Program\Qt\mkspecs\features\moc.prf:
..\..\..\..\Program\Qt\mkspecs\features\win32\windows.prf:
..\..\..\..\Program\Qt\mkspecs\features\resources.prf:
..\..\..\..\Program\Qt\mkspecs\features\uic.prf:
..\..\..\..\Program\Qt\mkspecs\features\yacc.prf:
..\..\..\..\Program\Qt\mkspecs\features\lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile x86emu-qt.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) "release\x86emu-qt.intermediate.manifest"
	-$(DEL_FILE) x86emu-qt.exp
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
